/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-09 02:38:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_005flist_005fcs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/layout/header.jspf", Long.valueOf(1725792806775L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1724403605343L));
    _jspx_dependants.put("jar:file:/C:/Users/ICT01-21/Desktop/miniProject%2009-03/miniProject%2009-08pm08.24/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/miniProject2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/layout/footer.jspf", Long.valueOf(1725708625814L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DANDI</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- 슬릭슬라이더 -->\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<!--slick slider 필요 태그 st-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.8/slick-theme.min.css\">\r\n");
      out.write("<!-- jQuery CDN -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<!-- slick Carousel CDN -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--폰트-->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;300;400;500;600;700;800;900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mini/css/header.css\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("         $('.autoplay').slick({\r\n");
      out.write("            centerMode: true,\r\n");
      out.write("            slidesToShow: 4,\r\n");
      out.write("            slidesToScroll: 1,\r\n");
      out.write("            autoplay: true,\r\n");
      out.write("            autoplaySpeed: 2000,\r\n");
      out.write("           \r\n");
      out.write("            draggable:true ,\r\n");
      out.write("            infinite: true\r\n");
      out.write("         });\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("      $('.center').slick({\r\n");
      out.write("         centerMode: true,\r\n");
      out.write("         centerPadding: '60px',\r\n");
      out.write("         slidesToShow: 5,\r\n");
      out.write("         autoplay: true,\r\n");
      out.write("         autoplaySpeed: 2000,\r\n");
      out.write("       \r\n");
      out.write("         draggable:true ,\r\n");
      out.write("         infinite: true,\r\n");
      out.write("         responsive: [\r\n");
      out.write("         {\r\n");
      out.write("            breakpoint: 768,\r\n");
      out.write("            settings: {\r\n");
      out.write("            arrows: false,\r\n");
      out.write("            centerMode: true,\r\n");
      out.write("            centerPadding: '40px',\r\n");
      out.write("            slidesToShow: 3\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("            breakpoint: 480,\r\n");
      out.write("            settings: {\r\n");
      out.write("            arrows: false,\r\n");
      out.write("            centerMode: true,\r\n");
      out.write("            centerPadding: '40px',\r\n");
      out.write("            slidesToShow: 1\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      ]\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("          // 스크롤 시 header fade-in\r\n");
      out.write("          $(document).on('scroll', function(){\r\n");
      out.write("              if($(window).scrollTop() > 100){\r\n");
      out.write("                  $(\"#header\").removeClass(\"deactive\");\r\n");
      out.write("                  $(\"#header\").addClass(\"active\");\r\n");
      out.write("              }else{\r\n");
      out.write("                  $(\"#header\").removeClass(\"active\");\r\n");
      out.write("                  $(\"#header\").addClass(\"deactive\");\r\n");
      out.write("              }\r\n");
      out.write("          })\r\n");
      out.write("      \r\n");
      out.write("      });\r\n");
      out.write("   function openLoginPopup() {\r\n");
      out.write("       window.open('/mini/mypage/login', 'LoginPopup', 'width=465, height=525 ,left=1200, top=150');\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function joinPopup(){\r\n");
      out.write("       window.open('/mini/mypage/join', 'JoinPopup', 'width=530, height=930 ,left=1200, top=80');\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function findIdPopup(){\r\n");
      out.write("       window.open('/mini/mypage/findId', 'findIdPopup', 'width=465, height=525 ,left=1200, top=150');\r\n");
      out.write("   }\r\n");
      out.write("   function findPwdPopup(){\r\n");
      out.write("       window.open('/mini/mypage/findPwd', 'findPwdPopup', 'width=465, height=525 ,left=1200, top=150');\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function loginClosed() {\r\n");
      out.write("       // 로그인 처리 로직\r\n");
      out.write("       // 예를 들어, resultVo를 통해 사용자 정보를 가져왔다고 가정합니다.\r\n");
      out.write("       const userId = resultVo.getUserid();\r\n");
      out.write("       const userName = resultVo.getUsername();\r\n");
      out.write("       \r\n");
      out.write("       // 세션에 로그인 상태 저장 (예시로 localStorage 사용)\r\n");
      out.write("       session.setAttribute(\"logId\", resultVo.getUserid());\r\n");
      out.write("      session.setAttribute(\"logName\", resultVo.getUsername());\r\n");
      out.write("      session.setAttribute(\"logStatus\", \"Y\");\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("       // 메인 페이지의 로컬 스토리지 업데이트 및 로그인 상태 갱신\r\n");
      out.write("       if (window.opener && !window.opener.closed) {\r\n");
      out.write("           window.opener.updateLoginStatus(userId, userName);\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       // 팝업 창 닫기\r\n");
      out.write("       window.close();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" ");

    Boolean excludeHeader = (Boolean) request.getAttribute("excludeHeader");

    if (excludeHeader == null || !excludeHeader) {

      out.write("\r\n");
      out.write("   <header>\r\n");
      out.write("       <div id=\"header\" class=\"deactive\">\r\n");
      out.write("         <h1 class=\"title\">\r\n");
      out.write("            <a href=\"/mini/\"><img src=\"/mini/images/main/logo.png\"></a>\r\n");
      out.write("         </h1>\r\n");
      out.write("         <!--검색창구현-->\r\n");
      out.write("         <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li><a href=\"/mini/festival/festivalList\">Festival</a></li>\r\n");
      out.write("               <li><a href=\"/mini/rest/restList\">Food</a></li>\r\n");
      out.write("               <li><a href=\"/mini/course/courseList\">Course</a></li>\r\n");
      out.write("               <li><a href=\"/mini/calendar/cal\">Calendar</a></li>\r\n");
      out.write("\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("         </nav>\r\n");
      out.write("      </div> \r\n");
      out.write("   </header>\r\n");

    }

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".mypageFavFrm{\r\n");
      out.write("display: flex;\r\n");
      out.write("   flex-direction: column;\r\n");
      out.write("    height: auto;\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("    margin: 150px auto;\r\n");
      out.write("    padding: 100px 20px 200px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageFavName a{\r\n");
      out.write("outline: none;             /* 포커스 아웃라인 제거 */\r\n");
      out.write("    text-decoration: none;     /* 밑줄 제거 (필요한 경우) */\r\n");
      out.write("    color: #999;  \r\n");
      out.write("    font-size:1.5em;\r\n");
      out.write("}\r\n");
      out.write(".mypageFavTop h2{\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write(" font-size:2.5em;\r\n");
      out.write("}\r\n");
      out.write(".mypageFavTop{\r\n");
      out.write("position: relative;\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("}\r\n");
      out.write(".mypageFavMain{\r\n");
      out.write("position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 24px;\r\n");
      out.write("}\r\n");
      out.write(".box_leftType1 {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 900px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".box_rightType1 {\r\n");
      out.write("    float: right;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write(" .snb_mypage {\r\n");
      out.write(" width: 248px;\r\n");
      out.write(" padding: 30px 20px 30px 0px;\r\n");
      out.write(" background: #f7f7f7;\r\n");
      out.write(" }\r\n");
      out.write(" .snb_mypage ul{\r\n");
      out.write(" 	list-style: none;  \r\n");
      out.write(" 	padding:0;\r\n");
      out.write(" }\r\n");
      out.write(" .snb_mypage > ul > li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write(" .snb_mypage a{\r\n");
      out.write(" 	color: black;    \r\n");
      out.write(" 	 outline: none;             /* 포커스 아웃라인 제거 */\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write(" }\r\n");
      out.write(" .snb_mypage ul li {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("   }\r\n");
      out.write("   .snb_mypage ul li.on a {\r\n");
      out.write("    background: url(../images/mypage/redline.png) 0 0 no-repeat;\r\n");
      out.write("    background-size: 4px 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .total_check {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 900px;\r\n");
      out.write("    padding: 15px 0 13px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    border-top: 1px solid #999;\r\n");
      out.write("    }\r\n");
      out.write("    .total_check strong span {\r\n");
      out.write("    padding: 0 2px;\r\n");
      out.write("    color: #0a97cd;\r\n");
      out.write("	}\r\n");
      out.write("	.total_check strong {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    }\r\n");
      out.write("	.list_thumType > li.bdr_nor {\r\n");
      out.write("    border-top: 1px solid #e6e6e6;\r\n");
      out.write("    width:900px;\r\n");
      out.write("     display: flex;  /* Flexbox를 사용하여 수평 배치 */\r\n");
      out.write("     align-items: center;\r\n");
      out.write("    gap: 20px; /* 이미지와 텍스트 간의 간격 조정 */\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.list_thumType > li.bdr_nor .date{\r\n");
      out.write("	  align-self: flex-start;\r\n");
      out.write("	}\r\n");
      out.write("	.list_thumType > li .photo .dim {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 48px;\r\n");
      out.write("    height: 28px;\r\n");
      out.write("    background: #13294b;\r\n");
      out.write("    line-height: 2;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.list_thumType > li .photo .txt_mid {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("	.list_thumType > li .area_txt {\r\n");
      out.write("   padding-right: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.list_thumType > li .area_txt .tit {\r\n");
      out.write("    margin-top: -5px;\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bdr_nor{\r\n");
      out.write("    list-style: none;  \r\n");
      out.write("	}\r\n");
      out.write("	.box_leftType1 ul{\r\n");
      out.write("	padding:0;\r\n");
      out.write("	}\r\n");
      out.write("	.pop_subMenu ul{\r\n");
      out.write("	list-style: none;  \r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	.pop_subMenu ul li{\r\n");
      out.write("	color: black;    \r\n");
      out.write(" 	 outline: none;             /* 포커스 아웃라인 제거 */\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("   .dotbutton button{\r\n");
      out.write("    background: none;  /* 배경 제거 */\r\n");
      out.write("    border: none;      /* 테두리 제거 */\r\n");
      out.write("    padding: 0;        /* 여백 제거 */\r\n");
      out.write("    margin: 0;         /* 외부 여백 제거 */\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("    .dotbutton button img{\r\n");
      out.write("      width: 25px;       /* 이미지의 크기를 조절 */\r\n");
      out.write("    height: auto;      /* 이미지의 비율을 유지 */\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("    .pop_subMenu a {\r\n");
      out.write("    outline: none;             /* 포커스 아웃라인 제거 */\r\n");
      out.write("    text-decoration: none;     /* 밑줄 제거 (필요한 경우) */\r\n");
      out.write("    color: black;              /* 글자색을 항상 검정색으로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pop_subMenu ul {\r\n");
      out.write("    padding: 0;                /* 불필요한 패딩 제거 */\r\n");
      out.write("    margin: 0;                 /* 불필요한 마진 제거 */\r\n");
      out.write("    list-style: none;          /* 목록 스타일 제거 (기본 점, 숫자 등) */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pop_subMenu li {\r\n");
      out.write("    padding: 0;                /* li 요소의 기본 패딩 제거 */\r\n");
      out.write("    margin-left:5px;\r\n");
      out.write("}\r\n");
      out.write(".pop_subMenu {\r\n");
      out.write("     display: none;\r\n");
      out.write("    border: 1px solid #BABABA;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    background-color:#F7F7F7;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    position: absolute; /* 절대 위치 지정 */\r\n");
      out.write("    top: 80px; /* 초기 위치 (위쪽에서 50px) */\r\n");
      out.write("    left: 500px; /* 초기 위치 (왼쪽에서 50px) */\r\n");
      out.write("}\r\n");
      out.write(".dotbutton button{\r\n");
      out.write(" margin-bottom: 10px;\r\n");
      out.write(" position: absolute; /* 절대 위치 사용 */\r\n");
      out.write("  top: 10; /* 위쪽 끝 */\r\n");
      out.write("  right:0; /* 오른쪽 끝 */\r\n");
      out.write("}\r\n");
      out.write(".photo{\r\n");
      out.write("	width: 220px;\r\n");
      out.write("    height: 126px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image img{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".image p{\r\n");
      out.write("  display: none; \r\n");
      out.write("}\r\n");
      out.write(".area_txt {\r\n");
      out.write("    display: flex;  /* 텍스트 영역을 플렉스 컨테이너로 설정 */\r\n");
      out.write("    align-items: center; /* 수직 가운데 정렬 */\r\n");
      out.write("    flex-grow: 1;  /* 남은 공간을 차지하게 설정 */\r\n");
      out.write("}\r\n");
      out.write(".area_txt .tit a:hover {\r\n");
      out.write("        border-bottom: 2px solid black; /* 마우스를 갖대었을 때 검정색 밑줄 */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function toggleDiv() {\r\n");
      out.write("    var hiddenBox = document.getElementById('hidden_Menu');\r\n");
      out.write("    \r\n");
      out.write("    if (hiddenBox.style.display === 'none' || hiddenBox.style.display === '') {\r\n");
      out.write("        hiddenBox.style.display = 'block'; // 박스를 보여줍니다.\r\n");
      out.write("    } else {\r\n");
      out.write("        hiddenBox.style.display = 'none'; // 박스를 숨깁니다.\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"mypageFavFrm\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"mypageFavTop\">\r\n");
      out.write("			<div class=\"mypageFavName\">\r\n");
      out.write("				<a href=\"/mini/mypage/mypage\"> 마이페이지</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2>코스</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"mypageFavMain\">\r\n");
      out.write("			<!-- 썸네일 리스트 -->\r\n");
      out.write("			<div class=\"box_leftType1\">\r\n");
      out.write("				<div class=\"total_check\">\r\n");
      out.write("					\r\n");
      out.write("				</div> \r\n");
      out.write("				<!-- 명소,추천,코스,축제 -->\r\n");
      out.write("<ul class=\"list_thumType flnon\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- //명소,추천,코스,축제 -->\r\n");
      out.write("	\r\n");
      out.write("				<!-- paging -->\r\n");
      out.write("				<div class=\"page_box\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //paging -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //썸네일 리스트 -->\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"box_rightType1\">\r\n");
      out.write("				<!-- snb -->\r\n");
      out.write("				<div class=\"snb_mypage\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li ><a href=\"/mini/mypage/mypage_list_fav\">찜목록</a></li>\r\n");
      out.write("						<li class=\"on\"><a href=\"/mini/mypage/mypage_list_cs2\">코스</a></li>\r\n");
      out.write("						<li><a href=\"/mini/mypage/qnaList\" id=\"qna\">Q&A</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mini/css/footer.css\" type=\"text/css\"/>\r\n");

    Boolean excludeFooter = (Boolean) request.getAttribute("excludeFooter");
    if (excludeFooter == null || !excludeFooter) {

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("   <footer>\r\n");
      out.write("      <div class=\"inner\">\r\n");
      out.write("        <div class=\"footer-message\">부산의 축제와 맛집을 소개하는 웹사이트</div>\r\n");
      out.write("        <div class=\"footer-contact\">컨택: ict@google.com</div>\r\n");
      out.write("        <div class=\"footer-copyright\">Copyright 2024 All ⓒ rights reserved</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /layout/header.jspf(157,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logStatus != 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                   <li class=\"lo\"><a onclick=\"openLoginPopup()\"><img src=\"/mini/images/main/unjoin.png\" style=\"width:60px; height:60px;\"/></a></li>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /layout/header.jspf(160,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logStatus == 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                   <li class=\"lo\"><a href=\"/mini/mypage/mypage\"><img src=\"/mini/images/main/join.png\" style=\"width:60px; height:60px;\"/></a></li>\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mypage/mypage_list_cs.jsp(231,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("course");
      // /WEB-INF/views/mypage/mypage_list_cs.jsp(231,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/mypage_list_cs.jsp(231,4) '${course}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${course}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        <li class=\"bdr_nor\">\r\n");
            out.write("            <div class=\"photo\">\r\n");
            out.write("                <a href=\"/mini/course/courseView?news_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.news_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                    ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                </a>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"area_txt\">\r\n");
            out.write("                <div class=\"tit\">\r\n");
            out.write("                    <a href=\"/mini/course/courseView?news_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.news_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"color: black; text-decoration: none;\r\n");
            out.write("                     font-size:1.1em; font-weight: bold;\">\r\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                    </a>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"date\">\r\n");
            out.write("                작성일: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.writedate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("            </div>\r\n");
            out.write("        </li>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
